// Stub module for all @codemirror/* and @lezer/* imports in tests
export const EditorView = class { dom = document.createElement('div'); dispatch() {}; state = { doc: { toString() { return ''; } }, selection: { main: { head: 0 } }, sliceDoc() { return ''; } }; static contentAttributes = { of() {} }; static theme = () => []; static updateListener = { of() {} }; static editable = { of: () => [] }; };
export const drawSelection = () => [];
export const keymap = { of: () => [] };
export const lineNumbers = () => [];
export const highlightActiveLineGutter = () => [];
export const highlightSpecialChars = () => [];
export const rectangularSelection = () => [];
export const crosshairCursor = () => [];
export const highlightActiveLine = () => [];
export const Compartment = class { of(v) { return []; } reconfigure() { return []; } };
export const EditorState = { allowMultipleSelections: { of() {} } };
export const history = () => [];
export const defaultKeymap = [];
export const historyKeymap = [];
export const syntaxHighlighting = () => [];
export const defaultHighlightStyle = {};
export const HighlightStyle = { define: () => [] };
export const foldGutter = () => [];
export const indentOnInput = () => [];
export const bracketMatching = () => [];
export const foldKeymap = [];
export const autocompletion = () => [];
export const completionKeymap = [];
export const acceptCompletion = () => false;
export const closeBrackets = () => [];
export const closeBracketsKeymap = [];
export const searchKeymap = [];
export const highlightSelectionMatches = () => [];
export const sql = () => [];
export const SQLite = {};
export const schemaCompletionSource = () => () => null;
export const keywordCompletionSource = () => () => null;
export const markdown = () => [];
const tagFn = () => ({});
export const tags = new Proxy({}, { get: () => tagFn });
